server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/aitao
    username: root
    password: 123
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5  #每5秒获取一次服务列表
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #当你获取主机名，返回的不是主机名是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #心跳周期5秒
    lease-expiration-duration-in-seconds: 10 #心跳过期周期10秒